nome = str(input('Digite seu nome completo: ')).strip()
print('analisando seu nome...')
print('seu nome em letras maiusculas é {}'.format(nome.upper()))
print('seu nome em letras minusculas é {}'.format(nome.lower()))
print('seu nome tem {} letras'.format(len(nome) - nome.count(' ')))
print('seu primeiro nome tem {} letras'.format(nome.find(' ')))